[AssetEditorSubsystem]
CleanShutdown=True
OpenAssetsAtExit=/Game/Animation_FullHD.Animation_FullHD

[ContentBrowser]
ContentBrowserTab1.SelectedPaths=/Game

[/Script/UnrealEd.EditorLoadingSavingSettings]
RestoreOpenAssetTabsOnRestart=AlwaysRestore
AutoSaveTimeMinutes=60

[AssetEditorToolkitTabLocation]
/Game/Animantion_FullHD.Animation_FullHD=0

[EposSequencerEditor SequencerSettings]
TreeViewWidth=0.2

[LevelSequenceEditor SequencerSettings]
TreeViewWidth=0.2

[/Script/UnrealEd.LevelEditorViewportSettings]
bAllowArcballRotate=True
bOrbitCameraAroundSelection=True
MaterialForDroppedTextures=/Odyssey/Materials/OdysseyDefaultMaterial.OdysseyDefaultMaterial
MaterialParamsForDroppedTextures=((Base, "Texture"),(Normal, "Texture"),(Specular, "Texture"),(Emissive, "Texture"))

#Force Viewport to use Storyboard Viewport Mode at first launch
[SlateAdditionalLayoutConfig]
Viewport 1.LayoutType=FourPanes2x2
FourPanes2x2.Viewport 1.Percentages0=X=0.500 Y=0.500
FourPanes2x2.Viewport 1.Percentages1=X=0.500 Y=0.500
FourPanes2x2.Viewport 1.Percentages2=X=0.500 Y=0.500
FourPanes2x2.Viewport 1.Percentages3=X=0.500 Y=0.500
FourPanes2x2.Viewport 1.Viewport0.TypeWithinLayout=Default
FourPanes2x2.Viewport 1.Viewport1.TypeWithinLayout=Storyboard
FourPanes2x2.Viewport 1.Viewport2.TypeWithinLayout=Default
FourPanes2x2.Viewport 1.Viewport3.TypeWithinLayout=Default
FourPanes2x2.Viewport 1.bIsMaximized=True
FourPanes2x2.Viewport 1.MaximizedViewport=FourPanes2x2.Viewport 1.Viewport1
